### ISSUE TITLE
Different Kaggle Dataset Support? 

### ISSUE THREAD

**Issue by juzjus10** [cj-mills/icevision-openvino-unity-tutorial#1]
Hello, is it possible to train the model using different dataset from kaggle? I'm planning to use ASL Handsign dataset for this. Thanks

**Comment by cj-mills** [comment]
Hi @juzjus10,
You can adapt the training code (specifically [the parser](https://christianjmills.com/posts/icevision-openvino-unity-tutorial/part-1/#create-dataset-parser)) for the target dataset, provided it has bounding box annotations. If the dataset only contains images with no bounding box annotations, it is not suitable for the model in this project.

Which Kaggle dataset do you want to use? If it is an image-only dataset, check out this [earlier tutorial](https://github.com/cj-mills/fastai-to-unity-tutorial) instead. It uses an image classification model rather than an object detection model.

If you want to use an image-only dataset for object detection, you can annotate the images using tools like [CVAT](https://github.com/opencv/cvat).

- [How to Label Images for Object Detection with CVAT](https://www.youtube.com/watch?v=OMgQ2JzOAWA)
